### ISSUE TITLE
broken for new project (pycharm)

### ISSUE THREAD

**Issue by pswenson** [aws/aws-toolkit-jetbrains#1159]
I had to create the directory missing in image to get past this (still failed but for different reason, see next issue)

pycharm 2019.2
aws toolkit 1.5

![image](https://user-images.githubusercontent.com/430370/62984606-1f375a00-bdf1-11e9-8b95-e41a6a43c3b0.png)

**Comment by pswenson** [comment]
update if I use a system interpreter instead of pipenv it appears to work

**Comment by zhangzhx** [comment]
I can reproduce this issue. A work around is to create this folder beforehand.

**Comment by OscarVanL** [comment]
Is this issue still unresolved? Might have a crack at it

**Comment by OscarVanL** [comment]
Ok, I've spent a few hours on this and think I'm getting close, but am still fairly confused!

I initially thought this may have been because the folder structure was not created properly, the error message makes it seem that way. I implemented some code in SamInitSelectionPanel.java, getNewProjectSettings() that checked if the directory existed, and if not, creates the directory.

        File projectDirectory = new File(generator.getStep().getLocationField().getText());
        if (!projectDirectory.exists()) {
            projectDirectory.mkdirs();
        }

**This did not fix the issue.**

I found what I think to really be the cause:

1. No reproduction:
* Go to New Project, AWS Serverless, then edit the location in the textbox to somewhere inside directories that do not already exist.
* Set Pipenv
* Do not change the runtime
* Click Create
- This will create successfully.

2. Reproduction:
* Go to New Project, AWS Serverless, then edit the location in the textbox to somewhere inside directories that do not already exist.
* Set Pipenv
* Change the runtime, eg: From python3.7 to 2.7, it doesn't matter, just as long as you change it.
* Click Create
* This will fail with the error in the original post.

Another peculiar thing you will observe is that the directory in the error message popup will be the one the Location box was initially, not what you edited it to be in the first step.

If you change the runtime, this makes getSdk() in PyCharmSdkSelectionPanel's sdkSelectionPanel.selectedPanel return null. It's as if switching the runtime recreates the Environment selection pane and some reference to it is not being updated properly?

I'd like to do some more digging tomorrow, but if you have any suggestions of areas to check I'm open to them :)

**Comment by OscarVanL** [comment]
There seems to be differing behaviour between Windows and Ubuntu (I'm running an Ubuntu VM to test). 

In Windows: If you change Runtime it will reset the Environment back to Virtualenv from Pipenv
In Ubuntu: If you change the Runtime **it does not reset the Environment back to Virtualenv.**

See the two videos below:
Windows:
![ezgif-2-752081e04a3b](https://user-images.githubusercontent.com/7999692/63578039-8e4a4680-c587-11e9-86e9-2aab9cd240b0.gif)
Ubuntu:
![ezgif-2-ebb4c31f9773](https://user-images.githubusercontent.com/7999692/63578053-93a79100-c587-11e9-980f-40fdc9590145.gif)

These were recorded in PyCharm 2019.2 Professional Edition.

**Comment by OscarVanL** [comment]
Some of this problem seems to come from the SdkSelectionPanel's listeners not being re-registered after it is recreated when the runtime is changed (in runtimeUpdate() and addSdkPanel() of SamInitSelectionPanel). If you add sdkSelectionUi.registerListeners() to the runtimeComboxBox listener, then this addresses some of the problem:

        runtimeComboBox.addItemListener(l -> {
            if (l.getStateChange() == ItemEvent.SELECTED) {
                runtimeUpdate();
                sdkSelectionUi.registerListeners();
            }
        });


I'm certain the issue is the SdkSelectionPanel not being recreated properly after the runtime is changed - I just can't pinpoint what it's missing.

**Comment by zhangzhx** [comment]
@OscarVanL Thanks for taking a look at this. I spent some time diving into this issue as well. In my case, even you don't change Runtime, this error still shows. I'm running the test on Mac. I think we just need to find a hook to put in the code you posted above before calling the `PyAddSdkGroupPanel`'s Create action.

**Comment by OscarVanL** [comment]
The reason I placed the registerListeners() call there was because if it's placed any earlier I get an `IllegalStateException myLocationField must not be null`, because the first line of registerListeners is `val document = step.getLocationField().textField.document`, which gets set later on.

Do you have any suggestions as to how the code should be rearranged to get around this issue?

**Comment by zhangzhx** [comment]
Well, the `registerListeners()` is a separate issue though. I just created a [separate issue](https://github.com/aws/aws-toolkit-jetbrains/issues/1179) for that. For this error dialog, we just need to hook in the folder creation logic before the call of `panel.getOrCreateSdk()`

**Comment by zhangzhx** [comment]
This was fixed in the [latest EAP version](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions) of the Toolkit. Can you give it a try?

Close this for now and feel free to reopen it or create a new one if you still see this issue.

**Comment by pswenson** [comment]
The error in question is gone, however the sample project files are not created.

**Comment by zhangzhx** [comment]
@pswenson It seems it is a separate issue. Can you create a new bug report for this one? It would be great if you can provide the detailed steps how we can reproduce.
